
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from '../context/Auth.Context'
import { NextRouter } from 'next/router';
import 'react-toastify/dist/ReactToastify.css';
import { UserProvider } from "@/context/User.Context";
import { CarsProvider } from "@/context/Cars.Context";



interface RootLayoutProps {
    children: React.ReactNode;
    router: NextRouter;
}

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({ children, router }: RootLayoutProps) {

    return (
        <html lang="en">

            <body className={inter.className}>

                <AuthProvider router={router}>
                    <UserProvider>
                      <CarsProvider>
                        {children}
                      </CarsProvider>
                    </UserProvider>
                </AuthProvider>

            </body>

        </html>
    );
}
